### PR TITLE
Improve viewer class (fully qualify ht_crypt, add tests & pdk update)

### PR DESCRIPTION
**Pull request by DLeich**
The viewer class was failing to compile when used on puppet 7.  This is because the ht_crypt function usage needed to be fully qualified.  While I was fixing this, I figured I might as well also add a basic spec test, which also required running `pdk update`.

### CODE REVIEW

**Comment by DLeich** [comment]
Hey folks - Just prodding this PR here.  Without the changes proposed in this PR, the viewer class is broken on modern versions of Puppet.

**Comment by SimonHoenscheid** [comment]
@DLeich The repo just migrated to Voxpupuli. Lets give this PR the love it deserves :-)

**Comment by DLeich** [comment]
I'm stuck in a loop trying to rebase this branch.  I'm going to redo my changes fresh and open a new PR.

**Comment by SimonHoenscheid** [comment]
@DLeich Maybe `git rerere` helps?

https://chuva-inc.com/blog/fast-tip-enable-git-rerere-right-now

**Comment by DLeich** [comment]
Closing this and replacing with https://github.com/voxpupuli/puppet-catalog-diff/pull/88

**Pull request closed without merging**
